language: ruby

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake test

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  # Don't add higher versions of Ruby!
  # Rails 3.x is not compatible with Ruby >= 2.2.0

env:
  - DB=sqlite
  - DB=mysql
  - DB=mysql2
  - DB=postgresql

before_script:
  - mysql -e 'create database filterrific_demo_test;'
  - psql -c 'create database filterrific_demo_test;' -U postgres

branches:
  except:
    - master
