sqlite: &sqlite
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 500

mysql: &mysql
  adapter: mysql
  database: filterrific_demo_<%= Rails.env %>
  username: root
  encoding: utf8

mysql2: &mysql2
  adapter: mysql2
  database: filterrific_demo_<%= Rails.env %>
  username: root
  encoding: utf8

postgresql: &postgresql
  adapter: postgresql
  database: filterrific_demo_<%= Rails.env %>
  username: postgres
  password:
  encoding: utf8

defaults: &defaults
  pool: 5
  timeout: 5000
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
